---
counts: # number of elements retrieved by a stream on the first access, 200 max
    global: 100
    unified: 100
    checkins: 100
    explore: 100
    mentions: 100
    posts: 100
    starred: 100
timeline:
    # if true, the timeline is displayed from old to recent
    downside: true 
    # if true, the unified timeline includes directed posts
    directed: true
    # number of stream posts displayed after a successful post
    streamback: 30
    countdown_1: 5
    countdown_2: 15
    show_client: false
    show_symbols: true
files:
    ayadnfiles: "/ayadn/data"
    auto_save_sent_messages: false # auto backup your sent private messages
    auto_save_sent_posts: false
identity: # change this prefix in each folder for your username in you're using several ADN accounts (don't use "@")
    prefix: me
skipped: # posts matching these values won't show up
    sources: []
    hashtags: []
    mentions: []
pinboard:
  username:
  password:
