help = "\nOptions disponibles:\n\n".cyan
help += "- " + "stream ".green + "pour voir votre stream personnalisé\n\n" 
help += "- " + "global ".green + "pour voir le global stream\n\n" 
help += "- " + "infos @username ".green + "pour voir les informations de cet utilisateur\n\n"
help += "- " + "posts @username ".green + "pour voir les posts de cet utilisateur\n\n"
help += "- " + "mentions @username ".green + "pour voir les posts mentionnant cet utilisateur\n\n"
help += "- " + "stars @username ".green + "pour voir les posts favoris de cet utilisateur\n\n"
help += "- " + "tag motclé ".green + "pour chercher les hashtags (ne pas taper le '#')\n\n"
help += "- " + "help ".green + "ou " + "aide ".green + "pour afficher l'aide\n\n"
help += "La commande sans options affiche le Stream.\n\n\n".green
help += "Exemples d'utilisation :\n\n".cyan
help += "ayadn.rb stream\n".magenta
help += "ayadn.rb tag hello\n".magenta
help += "ayadn.rb posts @ericd\n".magenta
help += "\n"