@help = "\nOptions disponibles:\n\n".cyan
@help += "- " + "stream ".green + "pour voir votre stream\n\n" 
@help += "- " + "global ".green + "pour voir le stream global\n\n" 
@help += "- " + "infos @username ".green + "pour voir les informations de cet utilisateur\n\n"
@help += "- " + "posts @username ".green + "pour voir les posts de cet utilisateur\n\n"
@help += "- " + "mentions @username ".green + "pour voir les posts mentionnant cet utilisateur\n\n"
@help += "- " + "stars @username ".green + "pour voir les posts favoris de cet utilisateur\n\n"
@help += "- " + "tag keyword ".green + "pour chercher les hashtags (ne pas taper le '#')\n\n"
@help += "- " + "help ".green + "ou " + "aide ".green + "pour afficher l'aide\n\n\n"
@help += "- " + "write ".green + "ou " + "w ".green + "pour poster un texte (guillemets simples obligatoires)\n\n\n"
@help += "La commande sans options affiche le Stream.\n\n\n".green
@help += "Exemples d'utilisation :\n\n".cyan
@help += "ayadn.rb stream\n".magenta
@help += "ayadn.rb write ".magenta + '\'Bonjour ADN !\'' + "\n"
@help += "ayadn.rb tag music\n".magenta
@help += "ayadn.rb posts @ericd\n".magenta
@help += "\n"