#!/usr/bin/env ruby
# encoding: utf-8
class AyaDN
	class Tools
		def helpScreen
		    help = "USAGE: ".cyan + "ayadn ".pink + "+ " + "optional action ".green + "+ " + "optional target(s) ".green + "+ " + "optional value(s)\n\n".green
		    help << "- " + "without options: ".cyan + "\tdisplay your unified stream\n" #.rjust(50)
		    help << "- " + "write ".green + "+ [Enter key] ".magenta + "\tcreate a post\n" #.rjust(33)
		    help << "- " + "write ".green + "\"your text\" ".brown + "\tcreate a post\n" #.rjust(35)
		    help << "- " + "reply ".green + "PostID ".brown + "\t\treply to a post\n" #.rjust(42)
		    # help << "- " + "delete postID ".green + "to delete a post\n"
		    help << "- " + "pm ".green + "@username ".brown + "\t\tsend a private message\n"
		    help << "- " + "channels ".green + "\t\tdisplay private channels\n"
		    help << "- " + "messages ".green + "channelID ".brown + "\tdisplay private messages\n"
		    help << "- " + "search ".green + "word ".brown + "\t\tsearch for word(s)\n"
		    help << "- " + "tag ".green + "hashtag ".brown + "\t\tsearch for a hashtag\n"
		    # help << "- " + "star/unstar postID ".green + "to star/unstar a post\n"
		    # help << "- " + "repost/unrepost postID ".green + "to repost/unrepost a post\n"
		    # help << "- " + "infos @username/postID ".green + "to display detailed informations on a user or a post\n"
		    # help << "- " + "convo postID ".green + "to display the conversation around a post\n"
		    help << "- " + "posts ".green + "@username ".brown + "\tdisplay a user's posts\n"
		    help << "- " + "mentions ".green + "@username ".brown + "\tdisplay posts mentionning a user\n"
		    # help << "- " + "starred @username/postID ".green + "to display a user's starred posts / who starred a post\n"
		    # help << "- " + "reposted postID ".green + "to display who reposted a post\n"
		    # help << "- " + "interactions ".green + "to display a stream of your interactions\n"
		    help << "- " + "global/trending/checkins/conversations/photos ".green + "\tdisplay a stream\n"
		    # help << "- " + "follow/unfollow @username ".green + "to follow/unfollow a user\n"
		    # help << "- " + "mute/unmute @username ".green + "to mute/unmute a user\n"
		    #help << "- " + "save/load postID ".green + "to save/load a post locally\n"
		    help << "- " + "list/backup followings/followers/muted ".green + "@username/me ".brown + "\tlist/backup users\n"
		    help << "- " + "infos, delete, star/unstar, repost/unrepost, convo, starred, reposted ".green + "PostID\n".brown
		    help << "- " + "infos, starred, follow, unfollow, mute, unmute ".green + "@username\n".brown
		    #help << "- " + "help ".green + "\t\t\tdisplay this screen\n" 
		    help << "- " + "help/commands/webhelp".green + "\n\n"
		    #help << "- " + "tip: ".cyan + "some commands have a shortcut: w(rite), r(eply), s(earch), p(osts), m(entions), t(ag), c(onvo), i(nfos), h(elp)\n"
		    help << "- " + "Tip: put 'scroll' before a stream to use the scrolling feature\n\n".cyan
		    help << "Examples:\n\n".cyan
		    help << "ayadn \n"#.green + "(display your Unified stream)\n"
		    help << "ayadn write \n"#.green + "(write a post with a compose window)\n"
		    help << "ayadn write \'@ayadn Posting with AyaDN!\' \n"#.green + "(write a post instantly between double quotes)\n"
		    help << "ayadn reply 14805036 \n"#.green + "(reply to post n°14805036 with a compose window)\n"
		    help << "ayadn tag nowplaying \n"#.green + "(search for hashtag #nowplaying)\n"
		    help << "ayadn star 14805036 \n"#.green + "(star post n°14805036)\n"
		    help << "ayadn checkins \n"#.green + "(display the Checkins stream)\n"
		    help << "ayadn scroll global \n"
		    help << "ayadn follow @ayadn \n"#.green + "(follow user @ericd)\n"
		    help << "ayadn search ruby,json \n"#.green + "(search for posts with these words)\n"
		    #help << "ayadn list files \n"
		    help << "ayadn backup followings me \n"
		    help << "\n"
		    return help
		end
		def list_of_commands
		    commands = "\nList of commands: \n\n".cyan
		    commands << "ayadn\n"
		    commands << "ayadn scroll\n"
		    commands << "ayadn write\n"
		    commands << "ayadn write '@ericd Good morning Eric!'\n"
		    commands << "ayadn reply 15723266\n"
		    commands << "ayadn pm @ericd\n"
		    commands << "ayadn global\n"
		    commands << "ayadn scroll global\n"
		    commands << "ayadn checkins\n"
		    commands << "ayadn scroll checkins\n"
		    commands << "ayadn trending\n"
		    commands << "ayadn scroll trending\n"
		    commands << "ayadn photos\n"
		    commands << "ayadn scroll photos\n"
		    commands << "ayadn conversations\n"
		    commands << "ayadn scroll conversations\n"
		    commands << "ayadn mentions @ericd\n"
		    commands << "ayadn scroll mentions @ericd\n"
		    commands << "ayadn posts @ericd\n"
		    commands << "ayadn scroll posts @ericd\n"
		    commands << "ayadn starred @ericd\n"
		    commands << "ayadn starred 15723266\n"
		    commands << "ayadn reposted 15723266\n"
		    commands << "ayadn infos @ericd\n"
		    commands << "ayadn infos 15723266\n"
		    commands << "ayadn convo 15726105\n"
		    commands << "ayadn tag nowplaying\n"
		    commands << "ayadn follow @ericd\n"
		    commands << "ayadn unfollow @ericd\n"
		    commands << "ayadn mute @ericd\n"
		    commands << "ayadn unmute @ericd\n"
		    commands << "ayadn interactions\n"
		    commands << "ayadn list files\n"
		    commands << "ayadn list files all\n"
		    commands << "ayadn download 286458\n"
		    commands << "ayadn download 286458,286797\n"
		    commands << "ayadn upload /path/to/kitten.jpg\n"
		    commands << "ayadn private 286458\n"
		    commands << "ayadn public 286458\n"
		    commands << "ayadn delete-file 286458\n"
		    commands << "ayadn search ruby\n"
		    commands << "ayadn search ruby,json\n"
		    commands << "ayadn channels\n"
		    commands << "ayadn send 12345\n"
		    commands << "ayadn messages 12345\n"
		    commands << "ayadn messages 12345 all\n"
		    commands << "ayadn star 15723266\n"
		    commands << "ayadn unstar 15723266\n"
		    commands << "ayadn repost 15723266\n"
		    commands << "ayadn unrepost 15723266\n"
		    commands << "ayadn delete 12345678\n"
		    commands << "ayadn list muted\n"
		    commands << "ayadn list followings @ericd\n"
		    commands << "ayadn list followers @ericd\n"
		    commands << "ayadn backup muted\n"
		    commands << "ayadn backup followings @ericd\n"
		    commands << "ayadn backup followers @ericd\n"
		    commands << "ayadn save 15723266\n"
		    commands << "ayadn load 15723266\n"
		    commands << "ayadn skip-source add IFTTT\n"
		    commands << "ayadn skip-source remove IFTTT\n"
		    commands << "ayadn skip-source show\n"
		    commands << "ayadn skip-tag add sports\n"
		    commands << "ayadn skip-tag remove sports\n"
		    commands << "ayadn skip-tag show\n"
		    commands << "ayadn skip-mention add username\n"
		    commands << "ayadn skip-mention remove username\n"
		    commands << "ayadn skip-mention show\n"
		    commands << "ayadn pin 16864003 ruby,json\n"
		    commands << "ayadn reset pagination\n"
		    commands << "ayadn help\n"
		    commands << "ayadn commands\n"
		    commands << "ayadn webhelp\n"
		    commands << "ayadn random\n"
		    commands << "\n"
		    return commands
		end
	end
end